// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROmaderas.AccesoADatos;

#nullable disable

namespace PROmaderas.AccesoADatos.Migrations.Negocio
{
    [DbContext(typeof(Contexto))]
    [Migration("20260714070327_PLA_HU_018_014_013_Sprint4")]
    partial class PLA_HU_018_014_013_Sprint4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmpleadoAD", b =>
                {
                    b.Property<int?>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdEmpleado"));

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<int>("IdPuesto")
                        .HasColumnType("int");

                    b.Property<string>("JornadaLaboral")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MotivoSalida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoVacacionesInicial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmpleado");

                    b.ToTable("Empleado", "dbo");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.BitacoraAuditoriaAD", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Accion");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DireccionIP");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAccion");

                    b.Property<int?>("IdRegistroAfectado")
                        .HasColumnType("int")
                        .HasColumnName("IdRegistroAfectado");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TablaAfectada");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorAnterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorNuevo");

                    b.HasKey("IdBitacora");

                    b.ToTable("BitacoraAuditoria", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.ClienteAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CedulaJuridica");

                    b.Property<string>("CondicionPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CondicionPago");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Direccion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<bool>("Exonerado")
                        .HasColumnType("bit")
                        .HasColumnName("Exonerado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NombreCliente");

                    b.Property<decimal>("PorcentajeExoneracion")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PorcentajeExoneracion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.DeduccionInternaAD", b =>
                {
                    b.Property<int>("IdDeduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDeduccion"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPorcentaje")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdDeduccion");

                    b.ToTable("DeduccionInterna", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.EmpleadoDeduccionAD", b =>
                {
                    b.Property<int>("IdEmpleadoDeduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleadoDeduccion"));

                    b.Property<int>("IdDeduccion")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleadoDeduccion");

                    b.HasIndex("IdDeduccion");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("EmpleadoDeduccion", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.EmpleadoPolizaAD", b =>
                {
                    b.Property<int>("IdEmpleadoPoliza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleadoPoliza"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CAST(GETDATE() AS date)");

                    b.Property<DateTime?>("FechaExclusion")
                        .HasColumnType("date");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdPoliza")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleadoPoliza");

                    b.HasIndex("IdPoliza");

                    b.HasIndex("IdEmpleado", "IdPoliza")
                        .IsUnique();

                    b.ToTable("EmpleadoPoliza", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.FacturacionAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("Activa");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<decimal>("Exoneracion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Exoneracion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEmision");

                    b.Property<int>("IdUsuarioEmisor")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioEmisor");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Impuesto");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NumeroFactura");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("IdOrdenCompra");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SaldoPendiente");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.IncapacidadAD", b =>
                {
                    b.Property<int>("IdIncapacidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncapacidad"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Dias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EntidadEmisora")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCertificado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TipoIncapacidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIncapacidad");

                    b.HasIndex("NumeroCertificado")
                        .IsUnique();

                    b.HasIndex("IdEmpleado", "FechaInicio", "FechaFin", "Activa");

                    b.ToTable("Incapacidad", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.InventarioMovimientoAD", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMovimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaMovimiento");

                    b.Property<int?>("IdOrdenCompra")
                        .HasColumnType("int")
                        .HasColumnName("IdOrdenCompra");

                    b.Property<int?>("IdProduccion")
                        .HasColumnType("int")
                        .HasColumnName("IdProduccion");

                    b.Property<int>("IdTipoTarima")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTarima");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioRegistro");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Motivo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TipoMovimiento");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdOrdenCompra");

                    b.HasIndex("IdTipoTarima");

                    b.ToTable("InventarioMovimiento", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.LicenciaAD", b =>
                {
                    b.Property<int>("IdLicencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLicencia"));

                    b.Property<bool>("ConGoceSalarial")
                        .HasColumnType("bit");

                    b.Property<decimal>("Dias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLicencia");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Licencia", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.LiquidacionAD", b =>
                {
                    b.Property<int>("IdLiquidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLiquidacion"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<decimal>("AniosLaborados")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DiasVacacionesPendientes")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoAguinaldoProporcional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoCesantia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPreaviso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoVacaciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoSalida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OtrosMontos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioPromedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiquidacion")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdLiquidacion");

                    b.ToTable("Liquidacion", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PagoFacturaAD", b =>
                {
                    b.Property<int>("IdPagoFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPagoFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPagoFactura"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaPago");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FormaPago");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("IdFactura");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioRegistro");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Referencia");

                    b.HasKey("IdPagoFactura");

                    b.HasIndex("IdFactura");

                    b.ToTable("PagoFactura", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.ParametroPlanillaAD", b =>
                {
                    b.Property<int>("IdParametroPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametroPlanilla"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("NombreParametro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdParametroPlanilla");

                    b.ToTable("ParametroPlanilla", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PedidoAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdOrdenCompra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("Activa");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaOrden");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Impuesto");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NumeroOrden");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Observacion");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int")
                        .HasColumnName("IdVendedor");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("OrdenCompra", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PedidoDetalleAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdOrdenCompraDetalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("IdOrdenCompra");

                    b.Property<decimal>("PrecioUnit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTarima");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Subtotal");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenCompraDetalle", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PlanillaDetalleFinancieroAD", b =>
                {
                    b.Property<int>("IdPlanillaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPlanillaDetalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanillaDetalle"));

                    b.Property<string>("AdvertenciaPolizaINS")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("DeduccionCCSS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionRenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionesInternas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DetalleIncapacidad")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DetalleVacaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("DiasIncapacidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DiasVacaciones")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HorasExtra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HorasOrdinarias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleado");

                    b.Property<int>("IdPlanillaPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("IdPlanillaPeriodo");

                    b.Property<decimal>("MontoDiasIncapacidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoIncapacidad");

                    b.Property<decimal>("MontoHorasExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPagoPatronalIncapacidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoVacaciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RebajoIncapacidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SalarioNeto");

                    b.Property<bool>("TienePolizaINSVigente")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPlanillaDetalle");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdPlanillaPeriodo");

                    b.ToTable("PlanillaDetalle", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PlanillaPeriodoAD", b =>
                {
                    b.Property<int>("IdPlanillaPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPlanillaPeriodo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanillaPeriodo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaInicio");

                    b.Property<int>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("TipoPeriodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoPeriodo");

                    b.HasKey("IdPlanillaPeriodo");

                    b.ToTable("PlanillaPeriodo", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PolizaINSAD", b =>
                {
                    b.Property<int>("IdPoliza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPoliza"));

                    b.Property<string>("Aseguradora")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("INS");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal?>("MontoAsegurado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("Prima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPoliza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPoliza");

                    b.HasIndex("NumeroPoliza")
                        .IsUnique();

                    b.ToTable("PolizaINS", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.ProductoAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTarima");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Medida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Medida");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("StockMinimo");

                    b.HasKey("Id");

                    b.ToTable("TipoTarima", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PuestoAD", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int")
                        .HasColumnName("IdDepartamento");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombrePuesto");

                    b.HasKey("IdPuesto");

                    b.ToTable("Puesto", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.SalarioHistorialAD", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("JornadaLaboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioResponsable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("SalarioHistorial", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.UsuarioAD", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Correo");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleado");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.VacacionAD", b =>
                {
                    b.Property<int>("IdVacacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacacion"));

                    b.Property<decimal>("Dias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdVacacion");

                    b.ToTable("Vacacion", (string)null);
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.EmpleadoDeduccionAD", b =>
                {
                    b.HasOne("PROmaderas.Abstracciones.Models.DeduccionInternaAD", "Deduccion")
                        .WithMany()
                        .HasForeignKey("IdDeduccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpleadoAD", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deduccion");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.EmpleadoPolizaAD", b =>
                {
                    b.HasOne("EmpleadoAD", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROmaderas.Abstracciones.Models.PolizaINSAD", "Poliza")
                        .WithMany("EmpleadosAsignados")
                        .HasForeignKey("IdPoliza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.FacturacionAD", b =>
                {
                    b.HasOne("PROmaderas.Abstracciones.Models.ClienteAD", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROmaderas.Abstracciones.Models.PedidoAD", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.IncapacidadAD", b =>
                {
                    b.HasOne("EmpleadoAD", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.InventarioMovimientoAD", b =>
                {
                    b.HasOne("PROmaderas.Abstracciones.Models.PedidoAD", "OrdenCompra")
                        .WithMany()
                        .HasForeignKey("IdOrdenCompra");

                    b.HasOne("PROmaderas.Abstracciones.Models.ProductoAD", "Producto")
                        .WithMany()
                        .HasForeignKey("IdTipoTarima")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.LicenciaAD", b =>
                {
                    b.HasOne("EmpleadoAD", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PagoFacturaAD", b =>
                {
                    b.HasOne("PROmaderas.Abstracciones.Models.FacturacionAD", "Factura")
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PedidoAD", b =>
                {
                    b.HasOne("PROmaderas.Abstracciones.Models.ClienteAD", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PedidoDetalleAD", b =>
                {
                    b.HasOne("PROmaderas.Abstracciones.Models.PedidoAD", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROmaderas.Abstracciones.Models.ProductoAD", "Producto")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PlanillaDetalleFinancieroAD", b =>
                {
                    b.HasOne("EmpleadoAD", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROmaderas.Abstracciones.Models.PlanillaPeriodoAD", "Periodo")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPlanillaPeriodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.SalarioHistorialAD", b =>
                {
                    b.HasOne("EmpleadoAD", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.ClienteAD", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PedidoAD", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PlanillaPeriodoAD", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.PolizaINSAD", b =>
                {
                    b.Navigation("EmpleadosAsignados");
                });

            modelBuilder.Entity("PROmaderas.Abstracciones.Models.ProductoAD", b =>
                {
                    b.Navigation("PedidoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
